### ISSUE TITLE
Gulp error on Windows 7

### ISSUE THREAD

**Issue by mahlu** [shakyShane/jekyll-gulp-sass-browser-sync#15]
$ gulp
[19:16:51] Using gulpfile c:\Users\Mahlu\Desktop\i\gulpfile.js
[19:16:51] Starting 'sass'...
[19:16:51] Starting 'jekyll-build'...
[19:16:51] Starting 'watch'...
[19:16:51] Finished 'watch' after 14 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)

**Comment by mahlu** [comment]
Solved! using @sergiokopplin solution

Just change this:
return cp.spawn('jekyll', ['build'], {stdio: 'inherit'}).on('close', done);

for this:
return cp.exec('jekyll', ['build'], {stdio: 'inherit'}).on('close', done);

**Comment by sergiokopplin** [comment]
:+1:
