### ISSUE TITLE
Errors after command sudo npm install

### ISSUE THREAD

**Issue by nvcampen** [shakyShane/jekyll-gulp-sass-browser-sync#19]
Hey guys,

Just trying to install this nifty little plugin following DevTips video: 

https://www.youtube.com/watch?v=nY4kQssg3lw&index=5&list=PLqGj3iMvMa4KeBN2krBtcO3U90_7SOl-A

I get an error after:
- I am able to cd to my directory of the jekyll-gulp-... ...-master file
- I type in sudo npm install. I also tried without the sudo command, but that does not help either.

The main error seems to be:
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

Can anyone help here ?

**Comment by sliverdesign** [comment]
hi i have the same probleme 
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mac/Desktop/jekyll-gulp-sass-browser-sync-master/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
Build failed
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/Desktop/jekyll-gulp-sass-browser-sync-master/npm-debug.log
help us

**Comment by sliverdesign** [comment]
after install npm-sass ihave this 
npm WARN package.json Dependency 'browser-sync' exists in both dependencies and devDependencies, using 'browser-sync@^1.9.2' from dependencies
npm WARN package.json Dependency 'gulp' exists in both dependencies and devDependencies, using 'gulp@^3.9.0' from dependencies
npm WARN package.json Dependency 'gulp-autoprefixer' exists in both dependencies and devDependencies, using 'gulp-autoprefixer@^1.0.0' from dependencies

**Comment by nvcampen** [comment]
Yeah, exact the same problem here.

**Comment by mikaer86** [comment]
I also have the same problem, any solutions?

**Comment by nadiaeagle** [comment]
I have the same problem of sliver design too

**Comment by JoshAMacD** [comment]
I had the same issue so I did some playing around and had to install gulp-sass:  npm install gulp-sass --save-dev after that I also installed gulp locally to my project. This seemed to solve all my issues.

**Comment by nadiaeagle** [comment]
I tried that @JoshAMacD, now the problem is:
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Chiara/Desktop/jekyll-gulp-sass-browser-sync-master/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
Build failed
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Chiara/Desktop/jekyll-gulp-sass-browser-sync-master/npm-debug.log

**Comment by JoshAMacD** [comment]
I believe you need to do: npm install node-sass

I did this a while back for another error I had.

**Comment by nadiaeagle** [comment]
That worked! Thank you so much @JoshAMacD!

**Comment by Yan11** [comment]
how to do it for Windows please write step by step, I have a lot of errors??

**Comment by BarinsGhost** [comment]
@JoshAMacD thank you so much!

**Comment by san3091** [comment]
I'm having a similar problem. I tried npm install gulp-sass --save-dev, as well as npm install node-sass, to no avail. 

20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Santiago/Desktop/jekyll-gulp-sass-browser-sync-master/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Santiago/Desktop/jekyll-gulp-sass-browser-sync-master/npm-debug.log

**Comment by harrycresswell** [comment]
@san3091 make sure you cd to node_modules within your project before doing npm install gulp-sass --save-dev then npm install node-sass afterwards and then it should work.

**Comment by wicio** [comment]
Hi after install gull-sass I'm having the same problem, any solutions?

4131 verbose lifecycle node-sass@0.9.6~install: unsafe-perm in lifecycle true
4132 verbose lifecycle node-sass@0.9.6~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/wicio/projekty_stron/generator/jekyll-gulp-sass-browser-sync/node_modules/gulp-sass/node_modules/node-sass/node_modules/.bin:/home/wicio/projekty_stron/generator/jekyll-gulp-sass-browser-sync/node_modules/gulp-sass/node_modules/.bin:/home/wicio/projekty_stron/generator/jekyll-gulp-sass-browser-sync/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/wicio/.gem/ruby/2.2.0/bin:/home/wicio/.gem/ruby/2.2.0/bin
4133 verbose lifecycle node-sass@0.9.6~install: CWD: /home/wicio/projekty_stron/generator/jekyll-gulp-sass-browser-sync/node_modules/gulp-sass/node_modules/node-sass
4134 silly lifecycle node-sass@0.9.6~install: Args: [ '-c', 'node build.js' ]
4135 silly lifecycle node-sass@0.9.6~install: Returned: code: 1  signal: null
4136 info lifecycle node-sass@0.9.6~install: Failed to exec install script
4137 verbose unlock done using /home/wicio/.npm/_locks/staging-cd891b4024f5cf86.lock for /home/wicio/projekty_stron/generator/jekyll-gulp-sass-browser-sync/node_modules/.staging
4138 silly rollbackFailedOptional Starting
4139 silly rollbackFailedOptional Finishing
4140 silly runTopLevelLifecycles Starting
4141 silly runTopLevelLifecycles Finishing
4142 silly install printInstalled
4143 verbose stack Error: node-sass@0.9.6 install: `node build.js`
4143 verbose stack Exit status 1
4143 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
4143 verbose stack     at emitTwo (events.js:87:13)
4143 verbose stack     at EventEmitter.emit (events.js:172:7)
4143 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
4143 verbose stack     at emitTwo (events.js:87:13)
4143 verbose stack     at ChildProcess.emit (events.js:172:7)
4143 verbose stack     at maybeClose (internal/child_process.js:818:16)
4143 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
4144 verbose pkgid node-sass@0.9.6
4145 verbose cwd /home/wicio/projekty_stron/generator/jekyll-gulp-sass-browser-sync/node_modules
4146 error Linux 4.2.5-1-vfio
4147 error argv "/usr/bin/node" "/usr/bin/npm" "install" "gulp-sass" "--save-dev"
4148 error node v5.0.0
4149 error npm  v3.3.12
4150 error code ELIFECYCLE
4151 error node-sass@0.9.6 install: `node build.js`
4151 error Exit status 1
4152 error Failed at the node-sass@0.9.6 install script 'node build.js'.
4152 error Make sure you have the latest version of node.js and npm installed.
4152 error If you do, this is most likely a problem with the node-sass package,
4152 error not with npm itself.
4152 error Tell the author that this fails on your system:
4152 error     node build.js
4152 error You can get their info via:
4152 error     npm owner ls node-sass
4152 error There is likely additional logging output above.
4153 verbose exit [ 1, true ]
