### ISSUE TITLE
Script fails on Windows

### ISSUE THREAD

**Issue by maiertech** [shakyShane/jekyll-gulp-sass-browser-sync#2]
I have tried your script on Mac and it works fine. At work I have to use Windows and my setup is RubyInstaller 1.9.3-p545 with Node 0.10.26.

I get the following error, which seems related to the child process. Any idea what goes wrong?

```
[gulp] Using gulpfile c:\Users\<user>\Repositories\<projectname>\gulpfile.js
[gulp] Starting 'sass'...
[gulp] Finished 'sass' after 4.71 ms
[gulp] Starting 'jekyll-build'...
[gulp] Starting 'watch'...
[gulp] Finished 'watch' after 8.96 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by tatygrassini** [comment]
Installing another Ruby version worked for me (2.1.6).

**Comment by FTMMM** [comment]
[15:06:32] Task 'install' is not in your gulpfile
[15:06:32] Please check the documentation for proper gulpfile formatting

What should I do, can anyone help me ?

**Comment by digiprix** [comment]
it doesn't work on windows anyhow... using jekyll independently is good...

**Comment by AcarMeel** [comment]
Hi, When I run the command gulp and  my browser opens in localhost:3000 I get the error  'Cannot GET /'

**Comment by sergiokopplin** [comment]
@AcarMeel, did you checked another url like "localhost:3000/index.html"? Or maybe with your application folder. In my case my url is like "localhost:3000/app/index.html"

**Comment by AcarMeel** [comment]
@sergiokopplin  but in my   _site folder  I don't have any html file (index.html) . Is not compiling any html files just the styles.

**Comment by steven-to** [comment]
anyone found a solution for this script on Windows? I tried lots of methods but none seems to work, I'm using this on Windows 10. Thanks in advanced!

**Comment by steven-to** [comment]
This is my gulpfile for Jekyll to work with Gulp on Windows (10), anyone who want the script please feel free to download and use it and also Star the repo if you like it :)
Again thanks Shane for uploading the original work, mine just has different structures and modified gulpfile so it can work on Windows.

https://github.com/steven-to/gulp-jekyll-browsersync/blob/gh-pages/gulpfile.js

**Comment by agragregra** [comment]
My new build a starter project with Jekyll and other tools (Win, Mac, Lin): https://github.com/agragregra/jekyll-gulp-autoprefixer-sass-bourbon-jade-browser-sync﻿

**Comment by duzyn** [comment]
You can use gulp-shell to run jekyll or bunlde exec jekyll

```
var shell       = require('gulp-shell');

// Task for building blog when something changed:
gulp.task('jekyll-build', shell.task(['bundle exec jekyll build']));
// Or if you don't use bundle:
// gulp.task('build', shell.task(['jekyll build']));
```

**Comment by paulmelero** [comment]
nah, you shouldn't.

> "gulp-shell": "promotes anti-patterns, use gulp-exec or child_process"

 https://github.com/gulpjs/plugins/blob/master/src/blackList.json

**Comment by MuhammadSayedMorsi** [comment]
hi there! I face this problem and I tried to use the command line prompt with ruby. and worked!

**Comment by thanooshan** [comment]
Yeah! like @MuhammadSayedMorsi said windows users please use the 'command line prompt with ruby' to run the gulp. It will work!.
