### ISSUE TITLE
Please HELP us windows users :(

### ISSUE THREAD

**Issue by Cylion** [shakyShane/jekyll-gulp-sass-browser-sync#20]
So like every windows user trying to get this to work I really need help on this on. How can I get this to work? Lets start at the begin. I Install Ruby+RubyGems, DevKit, Pyrhon, Note.js and all the other things. Everything go's fine until gulp. I get a lot of errors on npm install and gulp just does not work. Is there no one that got it working? Can you please post one step by step guide? I have been doing this for 10 hours can't take it anymore.!

**Comment by Pietrex** [comment]
Hi, there is a problem with couple of things on windows (I'm currently using 8.1 64).
First you need to install all dependencies manually. You can find list of them in file called "package.json".
There are:
- gulp
- gulp-sass
- gulp-autoprefixer
- browser-sync - this is main issue.
To install browser-sync you should follow these instructions:
http://www.browsersync.io/docs/#windows-users
You also need python v.2xxx and node-gyp.

Then you need to change a line of code in gulpfile.js:
```
16 return cp.spawn('jekyll', ['build'], {stdio: 'inherit'}).on('close', done);
```
To:
```
16 return cp.spawn(jekyll.bat, ['build'], {stdio: 'inherit'}).on('close', done);
```

I had similar problems and finally I got all working.

**Comment by karanchahal** [comment]
I did all that you mentioned but I'm STILL getting an error
The exact bug report is as follow:
C:\Users\user\Desktop\jekyll-gulp-sass-browser-sync>gulp
[12:24:27] Using gulpfile ~\Desktop\jekyll-gulp-sass-browser-sync\gulpfile.js
[12:24:27] Starting 'sass'...
[12:24:27] Starting 'jekyll-build'...
[12:24:27] Starting 'watch'...
[12:24:27] Finished 'watch' after 17 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3

C:\Users\user\Desktop\jekyll-gulp-sass-browser-sync>

What should I do??

**Comment by Pietrex** [comment]
Looks like Windows couldn't run or find jekyll.
Have you installed jekyll properly?

**Comment by karanchahal** [comment]
Yeah I did gem install Jekyll it installed without any problems

**Comment by Pietrex** [comment]
If you type "jekyll.bat" into cmd, do you get response?

**Comment by agragregra** [comment]
My new build a starter project with Jekyll and other tools (Win, Mac, Lin): https://github.com/agragregra/jekyll-gulp-autoprefixer-sass-bourbon-jade-browser-sync﻿

**Comment by adictonator** [comment]
Is this problem been solved yet? Do we have any solution now?

**Comment by CodePenguin42** [comment]
Hello, big n00b here. I am trying to get this to work on windows 7 x64. I have followed all the instructions I can see relating to this topic and am still getting a funky error when I try to gulp...

"(node:4188) fs: re-evaluating native module sources is not supported. If you are
 using the graceful-fs module, please update it to a more recent version.
[20:55:08] Using gulpfile ~\Desktop\jekyll-gulp-sass-browser-sync-master\gulpfil
e.js
[20:55:08] Starting 'sass'...
[20:55:08] Starting 'jekyll-build'...
[20:55:08] 'jekyll-build' errored after 3.02 ms
[20:55:08] TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at Object.exports.spawn (child_process.js:380:9)
    at Gulp.<anonymous> (C:\Users\User\Desktop\jekyll-gulp-sass-browser-sync-mas
ter\gulpfile.js:15:15)
    at module.exports (C:\Users\User\Desktop\jekyll-gulp-sass-browser-sync-maste
r\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\User\Desktop\jekyll-gulp-sass-browse
r-sync-master\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\User\Desktop\jekyll-gulp-sass-browse
r-sync-master\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\User\Desktop\jekyll-gulp-sass-browser-s
ync-master\node_modules\orchestrator\index.js:134:8)
    at C:\Users\User\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
[20:55:09] Finished 'sass' after 289 ms
"

Please help! Sorry if this is a big post, I am not 100% what is ok to not include.

Thanks you!

**Comment by karanchahal** [comment]
doesn't work stop trying . i wasted 2 days on this. the project isn't maintained for windows

**Comment by BilleFash** [comment]
The best way of getting around this is to uninstall your whole dev environment and set up a clean dev environment in a separate folder where you install your Python(with dev kit as you will need that), Ruby etc. In that folder make a projects file and run all your project from there using cmd. This will negate the windows bullshit. Will post screenshots and instructions this week.

**Comment by AndrewKTyler** [comment]
The best way of getting around this is to uninstall your whole dev environment and set up a clean dev environment in a separate folder where you install your Python(with dev kit as you will need that), Ruby etc. In that folder make a projects file and run all your project from there using cmd. This will negate the windows bullshit. Will post screenshots and instructions this week.
