### ISSUE TITLE
Mac OS X 10.11 Issue

### ISSUE THREAD

**Issue by WhatsNewSaes** [shakyShane/jekyll-gulp-sass-browser-sync#24]
I'm having an issue when I try to npm install a new version of this, or run `gulp` on an existing version of this repo.

Has anyone anyone tried this on El Capitan? Not sure if that is the issue, but it's the only thing I can think of.

**Comment by Brawlzapper** [comment]
#Yup Dude, Not able to run this on ElCapitan I am getting this error 

Naman# gulp
[22:23:49] Using gulpfile ~/Desktop/ProjectIO/gulpfile.js
[22:23:49] Starting 'sass'...
[22:23:49] Starting 'jekyll-build'...
[22:23:49] Starting 'watch'...
[22:23:49] Finished 'watch' after 73 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

##when I try to change in My gulpfile.js 

  return cp.spawn('jekyll', ['build'], {stdio: 'inherit'})

to

    return cp.exec('jekyll', ['build'], {stdio: 'inherit'})

This the error stops. Might work for you. Just replace spawn with exec.

##But now I am getting this new error -

Naman# gulp
[22:26:41] Using gulpfile ~/Desktop/ProjectIO/gulpfile.js
[22:26:41] Starting 'sass'...
[22:26:41] Starting 'jekyll-build'...
[22:26:41] Starting 'watch'...
[22:26:42] Finished 'watch' after 108 ms
[22:26:42] 'jekyll-build' errored after 134 ms
[22:26:42] Error: 127
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/Nam/Desktop/ProjectIO/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/Nam/Desktop/ProjectIO/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Nam/Desktop/ProjectIO/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/Nam/Desktop/ProjectIO/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.emit (events.js:129:20)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
[22:26:42] Finished 'sass' after 447 ms
[22:26:42] Starting 'sass'...
[22:26:42] Finished 'sass' after 149 ms

**Comment by tiivonen** [comment]
I had the same issue with jekyll after upgrading to El Capitan. I re-installed rvm (sudo issues from earlier installs), latest ruby and upgraded to latest jekyll. Now everything works.

**Comment by WhatsNewSaes** [comment]
What i had to do was install homebrew, and then install ruby and jekyll through homebrew. Apparently 10.11 really cracks down on where you can install ruby programs in your system -- even when using sudo. Homebrew puts it in a "safe" place that el capitan likes

**Comment by karltaylor** [comment]
I changed the package.json devDependencies to load `gulp-sass": "^2.1.0"` rather than `"gulp-sass": "^0.7.3"` and it worked fine after that
