### ISSUE TITLE
jekyll-build error 

### ISSUE THREAD

**Issue by DECHIRICO** [shakyShane/jekyll-gulp-sass-browser-sync#28]
I'm having an issue ... Has anyone anyone had the same problem?

[22:38:52] Using gulpfile ~/Desktop/jekyll-gulp-sass-browser-sync-master/gulpfile.js
[22:38:52] Starting 'sass'...
[22:38:52] Starting 'jekyll-build'...
[22:38:52] Starting 'watch'...
[22:38:52] Finished 'watch' after 12 ms
[22:38:52] Finished 'sass' after 116 ms
Configuration file: /Users/Francesco/Desktop/jekyll-gulp-sass-browser-sync-master/_config.yml
            Source: /Users/Francesco/Desktop/jekyll-gulp-sass-browser-sync-master
       Destination: /Users/Francesco/Desktop/jekyll-gulp-sass-browser-sync-master/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Dependency Error: Yikes! It looks like you don't have redcarpet or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- redcarpet' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2014-04-20-welcome-to-jekyll.markdown':
                    redcarpet
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    redcarpet
[22:38:53] 'jekyll-build' errored after 379 ms

**Comment by ankerbachryhl** [comment]
How did you solve it?

**Comment by kaoussi** [comment]
How did you solve this please?

**Comment by kayspiegel** [comment]
Do you have the gem redcarpet installed? Check with `$ gem list` in your terminal and check if redpcarpet is listed. If not install it with `gem install redcarpet`.

**Comment by kaoussi** [comment]
Yeah

**Comment by kayspiegel** [comment]
Yeah what? redcarpet installed?

**Comment by kaoussi** [comment]
Yeah sorry, redcarpet installed

**Comment by kayspiegel** [comment]
Hmm, do you have Jekyll 3.x installed? As far as I know the redcarpet is no longer the default for Jekyll 3.x. Try switching the markdown to kramdown in your `_config.yml`.

**Comment by kaoussi** [comment]
thank you, it's working now, and yes I have already the latest version of jekyll installed.

**Comment by Micah789** [comment]
Hi i still have the problem with this error message:

[20:16:39] Using gulpfile ~/Desktop/micahkwaka.co.uk/gulpfile.js
[20:16:39] Starting 'sass'...
[20:16:39] Starting 'jekyll-build'...
[20:16:39] Starting 'watch'...
[20:16:39] Finished 'watch' after 111 ms
[20:16:39] 'jekyll-build' errored after 135 ms
[20:16:39] Error: 127
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/micahkwaka/Desktop/micahkwaka.co.uk/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/micahkwaka/Desktop/micahkwaka.co.uk/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/micahkwaka/Desktop/micahkwaka.co.uk/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/micahkwaka/Desktop/micahkwaka.co.uk/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
[20:16:39] Finished 'sass' after 445 ms
[20:16:39] Starting 'sass'...
[20:16:40] Finished 'sass' after 186 ms

Please anyone help? And i am using a Mac with version El Capitan.

**Comment by sanddy95** [comment]
[21:23:30] Starting 'sass'...
[21:23:30] Starting 'jekyll-build'...
[21:23:30] Starting 'watch'...
[21:23:30] Finished 'watch' after 28 ms
[21:23:30] Finished 'sass' after 212 ms
Configuration file: C:/Users/sande/Desktop/web- design/softwares/jekyll-gulp-sass-browser-sync-master/_config.yml
            Source: C:/Users/sande/Desktop/web- design/softwares/jekyll-gulp-sass-browser-sync-master
       Destination: C:/Users/sande/Desktop/web- design/softwares/jekyll-gulp-sass-browser-sync-master/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Exec format error - C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/pygments.rb-1.1.1/lib/pygments/mentos.py in C:/Users/sande/Desktop/web- design/softwares/jekyll-gulp-sass-browser-sync-master/_posts/2014-04-20-welcome-to-jekyll.markdown
jekyll 3.3.1 | Error:  Exec format error -  C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/pygments.rb-1.1.1/lib/pygments/mentos.py
[21:23:31] 'jekyll-build' errored after 902 ms
[21:23:31] Error: 1
    at formatError (C:\Users\sande\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\sande\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\sande\Desktop\web- design\softwares\jekyll-gulp-sass-browser-sync-master\node_modules\orchestrator\index.js:264:8)
    at C:\Users\sande\Desktop\web- design\softwares\jekyll-gulp-sass-browser-sync-master\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\sande\Desktop\web- design\softwares\jekyll-gulp-sass-browser-sync-master\node_modules\orchestrator\lib\runTask.js:21:8)
    at ChildProcess.cb (C:\Users\sande\Desktop\web- design\softwares\jekyll-gulp-sass-browser-sync-master\node_modules\orchestrator\lib\runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)

**Comment by sanddy95** [comment]
please help ? i am using windows 10

**Comment by gau1st** [comment]
> sanddy95 commented 5 days ago
[21:23:30] Starting 'sass'...
[21:23:30] Starting 'jekyll-build'...
[21:23:30] Starting 'watch'...
[21:23:30] Finished 'watch' after 28 ms
[21:23:30] Finished 'sass' after 212 ms
Configuration file: C:/Users/sande/Desktop/web- design/softwares/jekyll-gulp-sass-browser-sync-master/_config.yml
Source: C:/Users/sande/Desktop/web- design/softwares/jekyll-gulp-sass-browser-sync-master
Destination: C:/Users/sande/Desktop/web- design/softwares/jekyll-gulp-sass-browser-sync-master/_site
Incremental build: disabled. Enable with --incremental
Generating...
Liquid Exception: Exec format error - C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/pygments.rb-1.1.1/lib/pygments/mentos.py in C:/Users/sande/Desktop/web- design/softwares/jekyll-gulp-sass-browser-sync-master/_posts/2014-04-20-welcome-to-jekyll.markdown
jekyll 3.3.1 | Error: Exec format error - C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/pygments.rb-1.1.1/lib/pygments/mentos.py
[21:23:31] 'jekyll-build' errored after 902 ms
[21:23:31] Error: 1
at formatError (C:\Users\sande\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
at Gulp. (C:\Users\sande\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
at emitOne (events.js:96:13)
at Gulp.emit (events.js:188:7)
at Gulp.Orchestrator._emitTaskDone (C:\Users\sande\Desktop\web- design\softwares\jekyll-gulp-sass-browser-sync-master\node_modules\orchestrator\index.js:264:8)
at C:\Users\sande\Desktop\web- design\softwares\jekyll-gulp-sass-browser-sync-master\node_modules\orchestrator\index.js:275:23
at finish (C:\Users\sande\Desktop\web- design\softwares\jekyll-gulp-sass-browser-sync-master\node_modules\orchestrator\lib\runTask.js:21:8)
at ChildProcess.cb (C:\Users\sande\Desktop\web- design\softwares\jekyll-gulp-sass-browser-sync-master\node_modules\orchestrator\lib\runTask.js:29:3)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)

Hi sanddy95 try open _config.yml and change 'highlighter: pygments' to 'highlighter: pygments.rb', it works for me and i hope it works for you too.

**Comment by sanddy95** [comment]
thanks a lot @gau1st  it worked for me to.

**Comment by Spandan-Madan** [comment]
Having the same problem as @sanddy95 but the solution by @gau1st doesn't seem to be working.  That has no effect on the error. I'm on Mac OS Sierra.

**Comment by gau1st** [comment]
@SpandanMadanHarvardAccount i'm sorry i forgot to mention that my solution only works in Windows environtment. I don't know yet about solution in Mac Os environtment. Maybe you can try install pygments globally via npm.

**Comment by ghost** [comment]
Thank you @gau1st .

You just made my night! 

.rb - Do you know why it doesn't just work without the ruby extension being added in versions higher than v3.x?

**Comment by Po4991212** [comment]
Thank you so much @gau1st

**Comment by yc-codes** [comment]
Thanks  all of you Guys!!
After 132 times write **gulp** finally got the live site

**Comment by arrhmne** [comment]
@kayspiegel Thank u very much

**Comment by ghost** [comment]
> Do you have the gem redcarpet installed? Check with `$ gem list` in your terminal and check if redpcarpet is listed. If not install it with `gem install redcarpet`.

This worked on Linux!! Saved my life !!
