### ISSUE TITLE
 Unhandled 'error' event

### ISSUE THREAD

**Issue by EN88** [shakyShane/jekyll-gulp-sass-browser-sync#35]
[20:16:11] Using gulpfile ~\Desktop\hard\master\gulpfile.js
[20:16:11] Starting 'sass'...
[20:16:11] Starting 'jekyll-build'...
[20:16:11] Starting 'watch'...
[20:16:11] Finished 'watch' after 15 ms
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by ghost** [comment]
Check the command your system uses to launch jekyll, if it is something like **jekyll.ruby2.1** for example, instead of **jekyll** then you can modify the gulpfile.js file, line 7, like this:

`var jekyll   = process.platform === 'win32' ? 'jekyll.bat' : 'jekyll.ruby2.1';
`

Or you can maybe do something like that : 
`ln -s /path/to/jekyll.ruby2.1 /usr/local/bin/jekyll`

**Comment by ApolonHellas** [comment]
i have same problem 

events.js:154
      throw er; // Unhandled 'error' event
      ^
 Error: _scss\main.scss
undefined
    at options.error (C:\Users\JiĐ\Desktop\jekyll-gulp-sass-browser-sync-master\node_modules\node-sass\lib\index.js:277:32)

C:\Users\JiĐ\Desktop\jekyll-gulp-sass-browser-sync-master>C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:2:in`module:SafeYAML'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in`require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:131:in`module:SafeYAML'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:26:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in`require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll.rb:28:in`<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in`require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/bin/jekyll:6:in `<top (required)>'
        from C:/Ruby22-x64/bin/jekyll:23:in`load'
        from C:/Ruby22-x64/bin/jekyll:23:in `<main>'

but i can run "ln -s /path/to/jekyll.ruby2.1 /usr/local/bin/jekyll" coz it doesnt know about ln , and i try other command but with var jekyll = process.platform === 'win32' ? 'jekyll.bat' : 'jekyll.ruby2.2';

**Comment by ApolonHellas** [comment]
solved it ..

**Comment by izelmaras** [comment]
@ApolonHellas How?
