### ISSUE TITLE
Error during 'Gulp' — events.js:141   throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by didacus** [shakyShane/jekyll-gulp-sass-browser-sync#44]
Have anyone found a solution for the following error?
Thank you in advance.

[22:09:59] Using gulpfile ~/Desktop/jekyll-gulp-sass-browser-sync-master/gulpfile.js
[22:09:59] Starting 'sass'...
[22:09:59] Starting 'jekyll-build'...
[22:09:59] Starting 'watch'...
[22:09:59] Finished 'watch' after 16 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by DatScreamer** [comment]
I am getting this aswell. Check your versions in package.json.

**Comment by JaimeOverflow** [comment]
Avoid use gem install jekyll. Try sudo apt-get install jekyll ;)

**Comment by replaid** [comment]
I ran into this in a Travis build and found that I hadn't installed Jekyll at all. `sudo apt-get install jekyll` got me an error since Travis uses `rvm`. `gem install jekyll` worked perfectly.

**Comment by replaid** [comment]
I do suggest that a preflight step would allow a much better error message.
