### ISSUE TITLE
events.js:160       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by BlackRonz** [shakyShane/jekyll-gulp-sass-browser-sync#54]
Hi im new at this and im getting this error, any help? 
Thank you in advance :-D

[12:08:47] Using gulpfile ~\Desktop\jekyll-gulp-sass-browser-sync-master\jekyll-gulp-sass-browser-sync-master\gulpfile.js
[12:08:47] Starting 'sass'...
[12:08:47] Starting 'jekyll-build'...
[12:08:47] Starting 'watch'...
[12:08:47] Finished 'watch' after 15 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll.bat ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by ToddL1u** [comment]
this happened to me as well.... :/

**Comment by payton** [comment]
I am having this issue as well.  (Windows 10)

**Comment by sagpat** [comment]
Anybody found the solution for this..? This is driving me crazy..

**Comment by sstubblefield** [comment]
@sagpat @PaytonGarland @ToddL1u @BlackRonz Not sure if you saw issue #44, try `sudo apt-get install jekyll` instead of using the ruby gem for jekyll.

**Comment by j143** [comment]
I hope I am welcome here, the answer is available at https://github.com/j143/systemds-website/issues/3#issuecomment-658130013
