### ISSUE TITLE
jekyll-build error

### ISSUE THREAD

**Issue by kamilluis1** [shakyShane/jekyll-gulp-sass-browser-sync#61]
[22:49:41] Using gulpfile ~/Desktop/Main-KL/gulpfile.js
[22:49:41] Starting 'sass'...
[22:49:41] Starting 'jekyll-build'...
[22:49:41] Starting 'watch'...
[22:49:41] Finished 'watch' after 25 ms
[22:49:41] Finished 'sass' after 257 ms
Configuration file: /Users/kamillusio/Desktop/Main-KL/_config.yml
jekyll 3.4.4 | Error:  undefined method `key?' for "redcarpet":String
[22:49:41] 'jekyll-build' errored after 597 ms
[22:49:41] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/kamillusio/Desktop/Main-KL/node_modules/orchestrator/index.js:264:8)
    at /Users/kamillusio/Desktop/Main-KL/node_modules/orchestrator/index.js:275:23
    at finish (/Users/kamillusio/Desktop/Main-KL/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/kamillusio/Desktop/Main-KL/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)

**Comment by kamilluis1** [comment]
would you help me with this one?

**Comment by nextlevelshit** [comment]
@kamilluis1  try that:

```bash
[sudo] gem install redcarpet # only use sudo if it does not work without
```

**Comment by Reakktor** [comment]
You have to edit your _config.yml and add this line:

`markdown: kramdown` 
or
replace redcarpet for kramdown. redcarpet is not supported by git anymore.
