### ISSUE TITLE
'gulp error'

### ISSUE THREAD

**Issue by ghost** [shakyShane/jekyll-gulp-sass-browser-sync#63]
I'm following along with DevTips on youtube. I'm getting an error after using the 'gulp' command.
 
C:\Users\Fishloki91\Desktop\jekyll-gulp-sass-browser-sync-master>gulp
[23:34:46] Using gulpfile ~\Desktop\jekyll-gulp-sass-browser-sync-master\gulpfil
e.js
[23:34:46] Starting 'sass'...
[23:34:46] Starting 'jekyll-build'...
[23:34:46] Starting 'watch'...
[23:34:46] Finished 'watch' after 14 ms
[23:34:46] Finished 'sass' after 121 ms
Configuration file: C:/Users/Fishloki91/Desktop/jekyll-gulp-sass-browser-sync-ma
ster/_config.yml
            Source: C:/Users/Fishloki91/Desktop/jekyll-gulp-sass-browser-sync-ma
ster
       Destination: C:/Users/Fishloki91/Desktop/jekyll-gulp-sass-browser-sync-ma
ster/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Dependency Error: Yikes! It looks like you don't have pygments or one of its d
ependencies installed. In order to use Jekyll as currently configured, you'll ne
ed to install this gem. The full error message from Ruby is: 'cannot load such f
ile -- pygments' If you run into trouble, you can find helpful resources at http
s://jekyllrb.com/help/!
  Liquid Exception: pygments in C:/Users/Fishloki91/Desktop/jekyll-gulp-sass-bro
wser-sync-master/_posts/2014-04-20-welcome-to-jekyll.markdown
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    pygments
[23:34:47] 'jekyll-build' errored after 599 ms
[23:34:47] Error: 1
    at formatError (C:\Users\Fishloki91\AppData\Roaming\npm\node_modules\gulp\bi
n\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\Fishloki91\AppData\Roaming\npm\node_modules\gu
lp\bin\gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\Fishloki91\Desktop\jekyll-gulp-
sass-browser-sync-master\node_modules\orchestrator\index.js:264:8)
    at C:\Users\Fishloki91\Desktop\jekyll-gulp-sass-browser-sync-master\node_mod
ules\orchestrator\index.js:275:23
    at finish (C:\Users\Fishloki91\Desktop\jekyll-gulp-sass-browser-sync-master\
node_modules\orchestrator\lib\runTask.js:21:8)
    at ChildProcess.cb (C:\Users\Fishloki91\Desktop\jekyll-gulp-sass-browser-syn
c-master\node_modules\orchestrator\lib\runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)

**Comment by niranjannitesh** [comment]
@BizarreEnder  
You should install **pygments** by using 
`gem install pygments.rb`

**Comment by Nagu07** [comment]
While trying to install gem install pygments.rb I get the following error can you help

ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (vendor/pygments-main/scripts/debug_lexer.py, C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/pygments.rb-1.1.2/vendor/pygments-main/scripts/find_error.py)

**Comment by keloriane** [comment]
delete the pygmet line on your yml file you don't need it ;)
